# Generated by Django 5.2.7 on 2025-11-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivonotas",
            name="resumen_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
