# Generated by Django 5.2.7 on 2025-12-01 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_archivonotas_resumen_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteGenerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("grupal", "Grupal"), ("individual", "Individual")],
                        max_length=20,
                    ),
                ),
                ("estudiante", models.CharField(blank=True, max_length=255, null=True)),
                ("descripcion", models.CharField(max_length=500)),
                ("pdf_file", models.FileField(upload_to="reportes/")),
                ("json_data", models.JSONField()),
                ("narrativa", models.TextField()),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "archivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="myapp.archivonotas",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_generacion"],
            },
        ),
    ]
