# Generated by Django 5.2.7 on 2025-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_reportegenerado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivonotas",
            options={"ordering": ["-fecha_subida"]},
        ),
        migrations.AddField(
            model_name="archivonotas",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
